In [2]:
# Import dependencies
import pandas as pd
import numpy as np4

In [3]:
# Reaad CSV and convert to DataFrame 
products = pd.read_csv("./productos.csv")
products

,id,name,categ_id
0,39674,INT ACENTO EMP LED B 11W100-240V800LM,DISPOSITIVO / IOT
1,39684,INT ACENTO EMP LED N 11W100-240V800LM,DISPOSITIVO / IOT
2,39676,SERIE DE EXT 12W100-240VCA RGBWIFI(TUYA),DISPOSITIVO / IOT
3,39682,SERIE DE EXTERIOR 12W100-240VCA RGB WIFI,DISPOSITIVO / IOT
4,39675,INT ACENTO EMP LED 12W100-240V,ILUMINACION / ILUMINACION-REMODELACION
...,...,...,...
9116,28976,ZTE MF283U-ROUTER 0/00 BLANCO TARIFARIO,DISPOSITIVO / CELULAR / TARIFARIO
9117,30093,all,ACCESORIO
9118,26146,envio,TIEMPO AIRE
9119,39657,sim29,ACCESORIO
9120,30092,todos,ACCESORIO

In [4]:
# Dropping N/A values 
products = products.dropna()
products['categ_id'].unique()

# No N/A values

array(['DISPOSITIVO / IOT', 'ILUMINACION / ILUMINACION-REMODELACION',
       'ACCESORIO / BOCINA / GENERAL', 'ACCESORIO / CABLE / GENERAL',
       'ACCESORIO / GAMER', 'ACCESORIO / CARGADOR / PREMIUM',
       'ACCESORIO / AUDIFONO / GENERAL', 'ACCESORIO / SOPORTE',
       'MAYOREO / ACCESORIO-MAY', 'ACCESORIO / BOCINA',
       'ACCESORIO / CABLE / PREMIUM', 'ACCESORIO / CARGADOR / GENERAL',
       'ACCESORIO / BATERIA', 'ACCESORIO / MICA / GENERAL-HIDRO MATE',
       'ACCESORIO / AUDIFONO / PREMIUM', 'ACCESORIO / BOCINA / PREMIUM',
       'DISPOSITIVO / SMARTWATCH', 'DISPOSITIVO / CELULAR / TELCEL',
       'DISPOSITIVO / CELULAR / LIBRE',
       'DISPOSITIVO / CELULAR / MESA-EXP', 'DISPOSITIVO',
       'ACCESORIO / DIFUSOR', 'ACCESORIO / FUNDA / PREMIUM',
       'ACCESORIO / FUNDA / GENERAL / HONOR A',
       'ACCESORIO / FUNDA / GENERAL / IPHONE A',
       'ACCESORIO / FUNDA / GENERAL / IPHONE B',
       'ACCESORIO / FUNDA / GENERAL / MOTOROLA A',
       'ACCESORIO / FUNDA / GENERAL / OPPO A',
       'ACCESORIO / FUNDA / GENERAL / SAMSUNG A',
       'ACCESORIO / FUNDA / GENERAL / UNIVERSAL C',
       'ACCESORIO / FUNDA / GENERAL / UNIVERSAL A',
       'ACCESORIO / FUNDA / GENERAL / XIAOMI B',
       'ACCESORIO / FUNDA / GENERAL / XIAOMI A',
       'ACCESORIO / FUNDA / GENERAL / ZTE A',
       'ACCESORIO / FUNDA / GENERAL / ZTE B',
       'ACCESORIO / MICA / GENERAL-GLASS',
       'ACCESORIO / MICA / GENERAL-HIDRO BACTERIAL',
       'ACCESORIO / MICA / GENERAL-HIDRO TABLET',
       'ACCESORIO / MICA / GENERAL-HIDRO PRIVACIDAD',
       'ACCESORIO / MICA / GENERAL-HIDRO TRAS',
       'ACCESORIO / MICA / GENERAL-HIDRO UV', 'ACCESORIO / MEMORIA',
       'DISPOSITIVO / CELULAR / TARIFARIO', 'CHIP', 'TIEMPO AIRE',
       'ACCESORIO / Deliveries', 'ACCESORIO',
       'Gastos / Gastos Administración', 'Gastos / Gastos Ventas',
       'ACCESORIO / OTROS', 'Gastos', 'ACCESORIO / LAMPARA',
       'PROMOCIONAL', 'ACCESORIO / FUNDA / GENERAL', 'ACCESORIO / CORREA',
       'ACCESORIO / CARGADOR', 'Depreciación',
       'DEVOLUCIONES Y BONIFICACIONES',
       'Servicios para cotización / Servicios para cotizaciones',
       'Servicios para cotización',
       'ACCESORIO / FUNDA / GENERAL / ALCATEL C',
       'ACCESORIO / FUNDA / GENERAL / HISENSE C',
       'ACCESORIO / FUNDA / GENERAL / HUAWEI C',
       'ACCESORIO / FUNDA / GENERAL / HUAWEI A',
       'ACCESORIO / FUNDA / GENERAL / HUAWEI B',
       'ACCESORIO / FUNDA / GENERAL / IPHONE SILICON A',
       'ACCESORIO / FUNDA / GENERAL / IPHONE C',
       'ACCESORIO / FUNDA / GENERAL / IPHONE SILICON C',
       'ACCESORIO / FUNDA / GENERAL / IPHONE SILICON B',
       'ACCESORIO / FUNDA / GENERAL / LG C',
       'ACCESORIO / FUNDA / GENERAL / MOTOROLA C',
       'ACCESORIO / FUNDA / GENERAL / MOTOROLA B',
       'ACCESORIO / FUNDA / GENERAL / OPPO C',
       'ACCESORIO / FUNDA / GENERAL / OPPO B',
       'ACCESORIO / FUNDA / GENERAL / REALME C',
       'ACCESORIO / FUNDA / GENERAL / SAMSUNG B',
       'ACCESORIO / FUNDA / GENERAL / SAMSUNG C',
       'ACCESORIO / FUNDA / GENERAL / TCL C',
       'ACCESORIO / FUNDA / GENERAL / UNIVERSAL B',
       'ACCESORIO / FUNDA / GENERAL / VIVO C',
       'ACCESORIO / FUNDA / GENERAL / XIAOMI C',
       'ACCESORIO / FUNDA / GENERAL / ZTE C', 'DISPOSITIVO / TABLETA',
       'ACCESORIO / MICA / GENERAL-10D', 'ACCESORIO / MICA / GENERAL',
       'ACCESORIO / MICA / GENERAL-CERAMICA',
       'ACCESORIO / MICA / GENERAL-CERAMICA PRIV',
       'ACCESORIO / MICA / PREMIUM',
       'ACCESORIO / MICA / GENERAL-GLASS TABLET',
       'ACCESORIO / MICA / GENERAL-HIDRO DISEÑO'], dtype=object)

In [5]:
# Copying products dataframe
products1 = products.copy()

In [6]:
# Filtering 'DISPOSITIVO / CELULAR / LIBRE' and 'DISPOSITIVO / CELULAR / TELCEL'
products = products[ (products['categ_id'] == 'DISPOSITIVO / CELULAR / LIBRE')]
products1 = products1[ (products1['categ_id'] == 'DISPOSITIVO / CELULAR / TELCEL')]

In [7]:
# Concat dataframes and droping duplicates
frames = [products, products1]
products_clean = pd.concat(frames)
products_clean.drop_duplicates(['name'])

,id,name,categ_id
235,19127,ALC 5003A-1C 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
237,19129,ALC 5003A-1C 1/16 ROSA,DISPOSITIVO / CELULAR / LIBRE
238,19130,ALC 5033M 1/16 AZUL,DISPOSITIVO / CELULAR / LIBRE
240,19131,ALC 5033M 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
248,19159,APPLE IPHONE-11 4/128 AMA,DISPOSITIVO / CELULAR / LIBRE
...,...,...,...
9106,26058,ZTE LTE 8030 BLADE V30 VITA GRIS KIT,DISPOSITIVO / CELULAR / TELCEL
9108,26060,ZTE LTE 8030 BLADE V30 VITA VERDE KIT,DISPOSITIVO / CELULAR / TELCEL
9110,26063,ZTE LTE A7020 BLADE A7S AZUL KIT,DISPOSITIVO / CELULAR / TELCEL
9114,26073,ZTE LTE BLADE A520 DORADO KIT,DISPOSITIVO / CELULAR / TELCEL
9115,26074,ZTE LTE BLADE V10 VITA VERDE,DISPOSITIVO / CELULAR / TELCEL

In [8]:
# Verifying that filtering was done correctly
products_clean['categ_id'].unique()

array(['DISPOSITIVO / CELULAR / LIBRE', 'DISPOSITIVO / CELULAR / TELCEL'],
      dtype=object)

In [16]:
products_clean.rename(columns = {'product_id':'Product_ID'}, inplace = True)
products_clean.rename(columns = {'name':'Description'}, inplace = True)
products_clean

,Product_ID,Description,categ_id
235,19127,ALC 5003A-1C 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
236,19128,ALC 5003A-1C 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
237,19129,ALC 5003A-1C 1/16 ROSA,DISPOSITIVO / CELULAR / LIBRE
238,19130,ALC 5033M 1/16 AZUL,DISPOSITIVO / CELULAR / LIBRE
240,19131,ALC 5033M 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
...,...,...,...
9106,26058,ZTE LTE 8030 BLADE V30 VITA GRIS KIT,DISPOSITIVO / CELULAR / TELCEL
9108,26060,ZTE LTE 8030 BLADE V30 VITA VERDE KIT,DISPOSITIVO / CELULAR / TELCEL
9110,26063,ZTE LTE A7020 BLADE A7S AZUL KIT,DISPOSITIVO / CELULAR / TELCEL
9114,26073,ZTE LTE BLADE A520 DORADO KIT,DISPOSITIVO / CELULAR / TELCEL
9115,26074,ZTE LTE BLADE V10 VITA VERDE,DISPOSITIVO / CELULAR / TELCEL

In [18]:
products_clean = products_clean.reset_index(drop=True)
products_clean

,Product_ID,Description,categ_id
0,19127,ALC 5003A-1C 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
1,19128,ALC 5003A-1C 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
2,19129,ALC 5003A-1C 1/16 ROSA,DISPOSITIVO / CELULAR / LIBRE
3,19130,ALC 5033M 1/16 AZUL,DISPOSITIVO / CELULAR / LIBRE
4,19131,ALC 5033M 1/16 NEGRO,DISPOSITIVO / CELULAR / LIBRE
...,...,...,...
838,26058,ZTE LTE 8030 BLADE V30 VITA GRIS KIT,DISPOSITIVO / CELULAR / TELCEL
839,26060,ZTE LTE 8030 BLADE V30 VITA VERDE KIT,DISPOSITIVO / CELULAR / TELCEL
840,26063,ZTE LTE A7020 BLADE A7S AZUL KIT,DISPOSITIVO / CELULAR / TELCEL
841,26073,ZTE LTE BLADE A520 DORADO KIT,DISPOSITIVO / CELULAR / TELCEL
842,26074,ZTE LTE BLADE V10 VITA VERDE,DISPOSITIVO / CELULAR / TELCEL

In [19]:
# Creating new CSV file
products_clean.to_csv('./productos_clean.csv', index=False)